config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'products#index'
  get 'pages/home'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrapProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Bootstrap</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Home", pages_home_path %></li>
          <li><%= link_to "about", pages_about_path %></li>

        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
    <%= yield %>

  </div>



  </body>
</html>

app/views/pages/about.html.erb
    <div class="row">
        <div class="col-md-5">
            <h1>About</h1>
            <p class="text">
            Snow mizzen aye lad reef tack fire ship spyglass Jack Ketch trysail. Mizzen gangplank grog blossom careen bowsprit man-of-war gaff take a caulk mutiny gunwalls. Salmagundi yo-ho-ho booty topgallant tackle gun Yellow Jack ye clap of thunder knave.

            </p>
        </div>
        <div class="col-md-5">
            <h1>hi!</h1>
            <p class="text">
            Skysail mizzen yardarm scuttle pirate Pieces of Eight topmast tackle Brethren of the Coast gabion. Jury mast belay draft Letter of Marque ye Jack Ketch lateen sail yardarm tack gangway. Weigh anchor Letter of Marque schooner sutler come about lad ho port quarterdeck mizzen.

            </p>
        </div>
            <div class="col-md-3">
            <p class="text">Lugger hearties chase six pounders to go on account case shot gibbet warp starboard flogging. Chantey pink grog blossom bilge water nipperkin squiffy sutler cutlass hempen halter heave to. Furl Jolly Roger pinnace measured fer yer chains coxswain mutiny hardtack hulk reef killick.</p>
            </div>
            <div class="col-md-2"> In tincidunt feugiat mi, non auctor nibh molestie quis. In vulputate eros nibh, id gravida orci semper id. Nunc dictum orci non enim condimentum dignissim.
            </div>


    </div>
    <div class="row">
                <div class="col-md-10">
Proin tristique sagittis tortor, quis viverra mauris porta sit amet. Nullam gravida dolor ac dui fringilla varius. Praesent id lorem eu tortor interdum tempus. Duis id orci quis nibh consequat facilisis ac pretium nunc. Mauris interdum imperdiet eros eu fermentum. Cras sem augue, aliquam vel scelerisque nec, imperdiet eget mauris. Duis lobortis, elit a placerat pharetra, lacus eros tincidunt orci, facilisis vulputate neque odio at sapien. Proin mi quam, maximus in ex ac, consequat consequat turpis. Maecenas a magna aliquet, lobortis augue sed, faucibus sem. Vivamus pretium eu lacus id efficitur. Ut arcu nisl, egestas eu sapien quis, ultricies lacinia orci. Vivamus auctor tincidunt velit porta lacinia.


            </div>
    </div>

app/views/pages/home.html.erb
    <div class="row">
        <div class="col-md-5">
            <h1>Home</h1>
            <p class="text">
            Snow mizzen aye lad reef tack fire ship spyglass Jack Ketch trysail. Mizzen gangplank grog blossom careen bowsprit man-of-war gaff take a caulk mutiny gunwalls. Salmagundi yo-ho-ho booty topgallant tackle gun Yellow Jack ye clap of thunder knave.

            </p>
        </div>
        <div class="col-md-5">
            <h1>hi!</h1>
            <p class="text">
            Skysail mizzen yardarm scuttle pirate Pieces of Eight topmast tackle Brethren of the Coast gabion. Jury mast belay draft Letter of Marque ye Jack Ketch lateen sail yardarm tack gangway. Weigh anchor Letter of Marque schooner sutler come about lad ho port quarterdeck mizzen.

            </p>
        </div>
            <div class="col-md-3">
            <p class="text">Lugger hearties chase six pounders to go on account case shot gibbet warp starboard flogging. Chantey pink grog blossom bilge water nipperkin squiffy sutler cutlass hempen halter heave to. Furl Jolly Roger pinnace measured fer yer chains coxswain mutiny hardtack hulk reef killick.</p>
            </div>
            <div class="col-md-2"> In tincidunt feugiat mi, non auctor nibh molestie quis. In vulputate eros nibh, id gravida orci semper id. Nunc dictum orci non enim condimentum dignissim.
            </div>


    </div>
    <div class="row">
                <div class="col-md-10">
Proin tristique sagittis tortor, quis viverra mauris porta sit amet. Nullam gravida dolor ac dui fringilla varius. Praesent id lorem eu tortor interdum tempus. Duis id orci quis nibh consequat facilisis ac pretium nunc. Mauris interdum imperdiet eros eu fermentum. Cras sem augue, aliquam vel scelerisque nec, imperdiet eget mauris. Duis lobortis, elit a placerat pharetra, lacus eros tincidunt orci, facilisis vulputate neque odio at sapien. Proin mi quam, maximus in ex ac, consequat consequat turpis. Maecenas a magna aliquet, lobortis augue sed, faucibus sem. Vivamus pretium eu lacus id efficitur. Ut arcu nisl, egestas eu sapien quis, ultricies lacinia orci. Vivamus auctor tincidunt velit porta lacinia.


            </div>
    </div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name , class:'form-control'%>
  </div>

  <div class="field">
    <%= form.label :Precio %>
    <%= form.number_field :price,  class:'form-control' %>
  </div>

  <div class="actions">
    <br>
    <%= form.submit 'Ingresar', class:'btn btn-primary'  %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td> <span>$</span><%= product.price %></td>
        <td><%= link_to 'Ver', product %></td>
        <td><%= link_to 'Editar', edit_product_path(product) %></td>
        <td><%= link_to 'Eliminar', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo producto', new_product_path, class:'btn btn-primary' %>

app/views/products/new.html.erb
<h1>Nuevo producto</h1>

<div class="row">
    <div class="col-md-3">
    <%= render 'form', product: @product %>

    </div>
</div>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>